language: java
jdk:
  - openjdk11

# Travis CI를 어느 브랜치가 푸쉬될 때 수행할지 지정
branches:
  only:
    - main

# Travis CI 서버의 Home
# Gradle 을 통해 의존성을 받게 되면 이를 해당 디렉토리에 캐시하여, 같은 의존성은 다음 배포 시 다시 받지 않도록 설정
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

# main 브런치에 푸쉬되었을 때 수행하는 명령어
script: "./gradlew clean build"

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - b940608@gmail.com