version: 0.0 # CodeDeploy 버전, Project 버전과는 별개
os: linux
files:
  - source:  / # CodeDeploy 에서 전달해 준 파일 중 destination 으로 이동시킬 대상 ( 루트 경로 지정 시 전체 파일 )
    destination: /home/ubuntu/dev/zip/
    overwrite: yes

permissions: # codedeploy 에서 EC2 서버로 넘겨준 파일들을 모두 ubuntu 권한을 갖도록 한다.
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  ApplicationStart:
    - location: deploy.sh
      timeout: 60
      runas: ec2-user