version: 0.0 # CodeDeploy 버전, Project 버전과는 별개
os: linux
files:
  - source:  / # CodeDeploy 에서 전달해 준 파일 중 destination 으로 이동시킬 대상 ( 루트 경로 지정 시 전체 파일 )
    destination: /home/ubuntu/dev/zip
    overwrite: yes

