spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        #format_sql: true
        show_sql: true
        #hbm2ddl.auto: update
    generate-ddl: false
    open-in-view: false